name: Test

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - id: test
      run: |
        MATRIX_PARAMS_COMBINATIONS='
              {"foo": "foo-1", "bar": "bar-1"},
              {"foo": "foo-1", "bar": "bar-2"},
              {"foo": "foo-2", "bar": "bar-1"},
          '
        echo ::set-output name=matrix-combinations::[$MATRIX_PARAMS_COMBINATIONS]
    outputs:
      matrix-combinations: ${{ steps.test.outputs.matrix-combinations }}
  build:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix-combinations) }}
#         value: ["a","b","c"]
    steps:
      - run: |
          echo foo=${{ matrix.foo }}
          echo bar=${{ matrix.bar }}
